INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC01', 'C++ Programming', 72, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC02', 'Operating System and Software Development', 72, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC03', 'OOPS with JAVA', 112, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC04', 'DSA using JAVA', 72, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC05', 'Database Technologies', 72, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC06', 'Web Programming Technologies', 112, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC07', 'Web-based Java Programming', 104, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC08', 'Aptitude and Effective Communication', 80, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAC09', 'Project', 120, 'PG01');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA01', 'Linux Programming and Cloud Computing', 50, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA02', 'Python and  R programming', 80, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA03', 'OOPS with JAVA', 90, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA04', 'Statistics', 90, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA05', 'DBMS', 90, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA06', 'Big Data Technologies', 150, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA07', 'Data Visualization', 50, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA08', 'Machine Learning', 120, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA09', 'Aptitude and Effective Communication', 90, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DBDA10', 'Project', 90, 'PG02');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD01', 'Aptitude and Effective Communication', 90, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD02', 'DSA', 90, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD03', 'Embedded C programming', 120, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD04', 'Embedded Linux Device Drivers', 90, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD05', 'Internet of Things', 90, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD06', 'Microcontroller Programming and Interfacing', 120, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD07', 'Project and Seminar', 150, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD08', 'Real-time Operating Systems', 60, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DESD09', 'Embedded Operating Systems', 90, 'PG03');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI01', 'Fundamental of AI', 40, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI02', 'Mathematics for AI', 40, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI03', 'Java Programming', 60, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI04', 'Advance Programming using Python', 90, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI05', 'Data Analytics', 90, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI06', 'Machine Learning', 100, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI07', 'Deep Machine Learning', 90, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI08', 'Natural Language Processing and Computer Vision', 100, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI09', 'AI Compute Plateforms and Trends', 110, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI10', 'Aptitude and Effective Communication', 90, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DAI11', 'Project', 90, 'PG04');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS01', 'Fundamental of Computer Network', 80, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS02', 'Concepts of Operating System and Administration', 180, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS03', 'Security Concepts', 180, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS04', 'Compilance Audit', 30, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS05', 'Network Defence and Countermeasures', 70, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS06', 'Cyber Forensics', 44, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS07', 'Public key Infrastrucutre', 50, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS08', 'IT Infrastructure Mangement and DevOps', 86, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS09', 'Aptitude and Effective Communication', 90, 'PG05');
INSERT INTO subject (ID, `Name`, Completion_hours, CourseID) VALUES ('DITISS10', 'Project', 90, 'PG05');